/**
 * The root layout component for the application.
 * This component provides the overall structure and styling for the application layout. It includes a navbar, main content area, and a footer.
 *
 * @param children {ReactNode} - The child components to be rendered within the layout.
 * @returns {JSX.Element} The rendered root layout component.
 */
import Navbar from '@components/layout/navbar/navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import { ReactNode, Suspense } from 'react';
import Footer from '@components/layout/footer';

// Load the Inter font with the 'latin' subset
const inter = Inter({ subsets: ['latin'] });

// Metadata for the application.
export const metadata = {
  title: 'Demo Warehouse Software',
  description: 'Generated by create next app',
};

/**
 * RootLayout component.
 *
 * @param children {ReactNode} - The child components to be rendered within the layout.
 * @returns {JSX.Element} The rendered RootLayout component.
 */
export default async function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="es" className={inter.className}>
      <body className="bg-white text-black selection:bg-teal-300 dark:bg-black dark:text-white dark:selection:bg-fuchsia-600 dark:selection:text-white">
        <div className="min-h-screen flex flex-col">
          {/* @ts-expect-error Server Component */}
          <Navbar />
          <div className="flex-grow">
            <div className="max-w-3xl flex-grow pt-5 pb-20 sm:mx-auto">
              <Suspense>
                <main>{children}</main>
              </Suspense>
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
